// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/base/token": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "base"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "nickname, password",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"登录成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/manager": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "管理员密码修改",
                "responses": {
                    "200": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/manager/:id/passwd": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager"
                ],
                "summary": "管理员密码修改",
                "parameters": [
                    {
                        "description": "id, passwd, passwdNew",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ChangePasswd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/position": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "position"
                ],
                "summary": "获取RFID与地址对应表",
                "responses": {
                    "200": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "position"
                ],
                "summary": "新增RFID与地址关系",
                "parameters": [
                    {
                        "description": "-, rfid_id, position",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Position"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/position/:id": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "position"
                ],
                "summary": "修改RFID与地址关系",
                "parameters": [
                    {
                        "description": "-, rfid_id, position",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Position"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "position"
                ],
                "summary": "删除RFID与地址关系",
                "responses": {
                    "204": {
                        "description": "{\"success\":true, \"data\":{}, \"msg\":\"成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Position": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "position": {
                    "type": "string"
                },
                "rfid_id": {
                    "type": "integer"
                }
            }
        },
        "request.ChangePasswd": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "newPasswd": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Auto-Manager Dev API",
	Description: "This is swagger sample for auto-manager",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
